name: Deploy Crawly to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Deploy to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/crawly
        gcloud run deploy crawly-api           --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/crawly           --platform managed           --region us-central1           --allow-unauthenticated           --set-env-vars MONGODB_URI=${{ secrets.MONGODB_URI }},GCS_BUCKET=${{ secrets.GCS_BUCKET }}
