name: Deploy Crawly to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # ✅ Step 1: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # ✅ Step 2: Set up Google Cloud SDK (no credentials needed here anymore)
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      # ✅ Step 3: Build and deploy to Cloud Run
      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/crawly
          gcloud run deploy crawly-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/crawly \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars MONGODB_URI=${{ secrets.MONGODB_URI }},GCS_BUCKET=${{ secrets.GCS_BUCKET }}
